channels:
  - defaults
dependencies:
  - python=3.6.7
  - pip=19.0.3
  - numpy
  - pandas
  - pip:
    - pytest==4.6.3
    - pylint==2.3.1
    - flask==1.1.1
    - gunicorn==20.0.4
    - tensorflow==2.3.0
    - matplotlib==3.2.2
    - json5==0.9.5
    - pillow==7.2.0
    - transformers==2.11.0
    - grammarbot==0.2.0
    - textblob==0.15.3
    - regex
